name: Scrape

on:
  push:
  schedule:
    - cron: '15 6 * * MON'

jobs:
  scheduled:
    runs-on: ubuntu-22.04
    timeout-minutes: 100

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Scrape
      run: python scrape.py

    - name: Commit
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
